server:
  port: 8085

spring:
  application:
    name: organization-service

  datasource:
    url: jdbc:mysql://localhost:3306/teamflow_organization_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

jwt:
  secret: change-this-secret-in-a-secure-config-server
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info
